### ISSUE TITLE
Missing akka-persistence-dynamodb-base dependency artifact

### ISSUE THREAD

**Issue by dlagnohed** [j5ik2o/akka-persistence-dynamodb#147]
Using the `akka-persistence-dynamodb-journal` dependency in sbt fails with `not found: https://repo1.maven.org/maven2/com/github/j5ik2o/akka-persistence-dynamodb-base_2.13`
Maybe the artifact never got published?

**Comment by j5ik2o** [comment]
Sorry..., I made a mistake in deployment the JAR. That will be fixed in the next release. Thank you for your reporting.
https://github.com/j5ik2o/akka-persistence-dynamodb/pull/148

**Comment by j5ik2o** [comment]
https://github.com/j5ik2o/akka-persistence-dynamodb/releases/tag/v1.1.1
