### ISSUE TITLE
Suggested DynamoDB setup doesn't work with default configuration

### ISSUE THREAD

**Issue by MetalGuardian** [j5ik2o/akka-persistence-dynamodb#196]
Version `v1.1.3` with suggested dynamodb structure (which is `pkey`, `skey` as hash and range keys) is not working with default configuration of the plugin. At the same time it works with legacy db structure having default configuration (no override for `sort-key-column-name` and `legacy-config-layout` is not set)

**Comment by j5ik2o** [comment]
@MetalGuardian 
I can't find the cause of the problem with the information you provided. Can you provide the source code that is not working for you?

**Comment by MetalGuardian** [comment]
sorry for the delay. I'm still trying to understand what's actually failing there, I will update issue when I got some details

**Comment by j5ik2o** [comment]
This issue is old and will be closed. If you have problems again, please create a new issue.
