### ISSUE TITLE
"dynamo-db-journal" is confusingly close to "dynamodb-journal"

### ISSUE THREAD

**Issue by coreyoconnor** [j5ik2o/akka-persistence-dynamodb#23]
Non-blocker.

This is, equivalently, an issue with "dynamodb-journal". I'd prefer if both had clearly distinct names. EG: something like "j5ik2o-dynamodb-journal" and "akka-dynamodb-journal" respectively. 

Using a generic name like "dynamodb-journal"  is not appropriate IMO. There are several different ways even beyond the current implementations akka persistence could be implemented using dynamodb. I'd prefer to have a distinct prefix for each. This assists in a system using multiple persistence plugins without confusion.

That said, I see no issues with the implementations all having the package name "akka-persistence-dynamodb" as long as they are clearly from different organizations. The plugin identifier, however, does not have a similar organization scope.

In addition: without some mechanism to alias the prior plugin identifiers this kind of name change is going to be a challenge. Not sure if such a thing exists.

**Comment by j5ik2o** [comment]
@coreyoconnor 
Thank you for your opinion. 
Certainly, it looks like a mess with similar plugin ids. This product's ID will change, but please take time to find a good name.

**Comment by coreyoconnor** [comment]
Agreed. As the joke goes: "There are only two hard things in Computer
Science: cache invalidation and naming things. -- Phil Karlton"

:)

**Comment by j5ik2o** [comment]
Update plugin ids to`j5ik2o.dynamo-db-journal` and `j5ik2o.dynamo-db-snapshot` and `j5ik2o.dynamo-db-read-journal` since version 1.0.8.

https://github.com/j5ik2o/akka-persistence-dynamodb/blob/master/library/src/main/resources/reference.conf
