### ISSUE TITLE
[NotIssue] Question on Sequence based and PartitionId based key schemes

### ISSUE THREAD

**Issue by artur-jablonski** [j5ik2o/akka-persistence-dynamodb#243]
Hi, 

I am not sure where I can ask this question, so I open it here. 

I am trying to wrap my head around the two key schemes for events: the default sequence number based and the partition id based as explained in the [write sharding](https://github.com/j5ik2o/akka-persistence-dynamodb#write-sharding) section of the usage document.

Given an entity `MyEntity` with id `12345`, 5 events for that entity with sequence numbers 1-5 and 2 (default) write shards configured I understand that:

Under Sequence Number based scheme, the partition and sort key for the events will be as followed:

> Partition Key = ${persistenceId}-${sequenceNumber % shardCount}
> Sort Key = ${sequenceNumber}

seq | partition key | sort key
------------ | ------------- | ----------------
1 | MyEntity-12345-1 | 1
2 | MyEntity-12345-0 | 2
3 | MyEntity-12345-1 | 3
4 | MyEntity-12345-0 | 4
5 | MyEntity-12345-1 | 5

This means that half of events will end up in one dynamodb partition and the other half in another one. 

This means that when querying for events for that entity IN ORDER they occured, you need to query both partitions independently and merge the results based on the sort key.

Under PartitionId based scheme, the keys will be as followed (assuming `${md5(persistenceId.reverse) % shardCount}` is 0)

> Partition Key = ${persistenceId.prefix}-${md5(persistenceId.reverse) % shardCount}
> Sort Key = ${persistenceId.body}-${sequenceNumber}

seq | partition key | sort key
------------ | ------------- | ----------------
1 | MyEntity-0 | MyEntity-12345-1
2 | MyEntity-0 | MyEntity-12345-2
3 | MyEntity-0 | MyEntity-12345-3
4 | MyEntity-0 | MyEntity-12345-4
5 | MyEntity-0 | MyEntity-12345-5

This means that half of entities of MyEntity type will be in one dynamodb partition and the other half in another one. 

This means that all events of MyEntity entity with given id will be in the same dynamodb partition and that means when querying back for all events IN ORDER they occurred will require one query against one partition only.

The documentation states:

> If you want to load events chronologically in DynamoDB Streams, choose pattern-2.

pattern-2 being PartitionId based approach. I thought that events in dynamodb stream appear in order of modifications happenign on the table regardless of partition from [dynamod db streams doc](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Streams.html):

> DynamoDB Streams captures a time-ordered sequence of item-level modifications in any DynamoDB table and stores this information in a log for up to 24 hours

So how exactly the key scheme affects the ordering on the table stream?

Side question: What is the `reverse` in `persistence.reverse` for?

Thx

**Comment by j5ik2o** [comment]
> Given an entity MyEntity with id 12345, 5 events for that entity with sequence numbers 1-5 and 2 (default) write shards configured I understand that:

Your description is correct.

> pattern-2 being PartitionId based approach. I thought that events in dynamodb stream appear in order of modifications happenign on the table regardless of partition from dynamod db streams doc:

The partition key determines the partition in DynamoDB. The consumers that consume events on a Shard are also one-to-one with the Shard.This means that for all consumers to consume events in the full order of events, they must be coordinated so that events with the same ID are stored in the same partition.

Reference documentation is below:

https://aws.amazon.com/jp/blogs/news/how-to-perform-ordered-data-replication-between-applications-by-using-amazon-dynamodb-streams/

> Side question: What is the reverse in persistence.reverse for?

If the IDs contain sequential numbers or timestamp components, they may be stored in the same partition when calculated as is. To ensure that close IDs are distributed to different partitions, the `revserse` is used. (You can customize the calculation of the partition and sort keys)

**Comment by artur-jablonski** [comment]
Thank you for your response. 

I understand now that ordering issue. So this is to cover consuming the stream in parallel scenario. Makes sense. 

As for the `reverse`, because its result is passed to `md5` I cannot see the difference between `md5(persistenceId)` and `md5(persistenceId.reverse)` in terms of mitigating risk of "hot partition". I understand this can be customized. 

Thx
