### ISSUE TITLE
Documentation in scaladex show incorrect table name

### ISSUE THREAD

**Issue by rdias** [j5ik2o/akka-persistence-dynamodb#251]
Hi,
  
   I created the DynamoDB using the documentation of the site https://index.scala-lang.org/j5ik2o/akka-persistence-dynamodb/akka-persistence-dynamodb-snapshot/1.1.4?target=_2.13 and there in the section "DynamoDB Setup" the snapshot table name is "Snapshots" see that have a "s" on the end.  How I created my table using the name "Snapshots" I got this error: Caused by: java.util.concurrent.CompletionException: software.amazon.awssdk.services.dynamodb.model.ResourceNotFoundException: Requested resource not found (Service: DynamoDb, Status Code: 400, Request ID: A9T7T1IG5DRFO2B6KTSUMM3ECNVV4KQNSO5AEMVJF66Q9ASUAAJG, Extended Request ID: null)
 I changed my config to use "Snapshots" but seeing the code SnapshotPluginConfig.scala i saw that default is "Snapshot".

 I think that fix the documentation on scaladex site will be enough

Thanks

**Comment by j5ik2o** [comment]
@rdias
REAME.md is wrong and I would like to fix it. Please wait a while for the correction to take effect. Thanks for your report.
