### ISSUE TITLE
Unable to resolve dependency for Scala 2.13

### ISSUE THREAD

**Issue by agregoris-zd** [j5ik2o/akka-persistence-dynamodb#59]
Hello, I'm using Scala 2.13 and when I try to add this library as a dependency this is not resolved although the documentation says this version of Scala is supported. I didn't found any 2.13 release in the repositories https://mvnrepository.com/artifact/com.github.j5ik2o/akka-persistence-dynamodb

**Comment by j5ik2o** [comment]
Hi, thank you for your report! 2.13 target JAR has been deployed. Please try it.
